customers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.DriverListView.as_view(), name='list'),
	url(r'^create/', views.DriverCreateView.as_view(), name='create'),
	url(r'^(?P<pk>\d+)/$', views.DriverDetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/edit/$', views.DriverUpdateView.as_view(), name='update'),
	url(r'^(?P<pk>\d+)/delete/$', views.DriverDeleteView.as_view(), name='delete'),
]

pagkage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from customers.views import CustomerViewSet, PackageViewSet

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'customers', CustomerViewSet)
router.register(r'packages', PackageViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api_auth/', include('rest_framework.urls', namespace = 'rest_framework')),
    url(r'^$', views.Home.as_view(), name="home"),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^api/v1/customers/', include('customers.api_urls', namespace='customers_api')),
    url(r'^api/v2/', include(router.urls, namespace='api_v2')),

]

urlpatterns += staticfiles_urlpatterns()

customers/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Customer(models.Model):

	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	business_name = models.CharField(max_length=255)
	phone = models.IntegerField()
	email = models.EmailField()
	address_line_1 = models.CharField(max_length=255)
	address_line_2 = models.TextField(blank=True, default='')
	address_city = models.CharField(max_length=255)
	address_state = models.CharField(max_length=255)
	address_zipcode = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.first_name

class Package(models.Model):

	name = models.CharField(max_length=255)
	price = models.IntegerField()
	SKU = models.IntegerField()
	height = models.IntegerField()
	width = models.IntegerField()
	depth = models.IntegerField()
	weight = models.IntegerField()
	location = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	customer = models.ForeignKey(Customer, related_name="packages")

class Driver(models.Model):
	
	name = models.CharField(max_length=255)
	photo_url = models.URLField(unique=True)
	longitude = models.CharField(max_length=255)
	latitude = models.IntegerField()
	email = models.EmailField()
	address_line_1 = models.CharField(max_length=255)
	address_line_2 = models.TextField(blank=True, default='')
	address_city = models.CharField(max_length=255)
	address_state = models.CharField(max_length=255)
	address_zipcode = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)

	def get_absolute_url(self):
		return reverse("customers:detail", kwargs={"pk": self.pk})

customers/views.py
from django.views import generic
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from rest_framework import generics
from rest_framework import viewsets
from rest_framework import mixins
from rest_framework.decorators import detail_route
from rest_framework.response import Response
from rest_framework import permissions

from . import serializers
from builtins import (super)
from . import models


# ==============================================================================
# 							Driver View
# ==============================================================================


class DriverCreateView(generic.CreateView):
	fields = ("name", "photo_url", "longitude", "latitude", "email", "address_line_1", "address_line_2", "address_city", "address_state", "address_zipcode")
	model = models.Driver

class DriverListView(generic.ListView):
	model = models.Driver
	context_object_name = 'drivers'

class DriverDetailView(generic.DetailView):
	model = models.Driver

class DriverUpdateView(generic.UpdateView):
	fields = ("name", "photo_url", "longitude", "latitude", "email", "address_line_1", "address_line_2", "address_city", "address_state", "address_zipcode")
	model = models.Driver

class DriverDeleteView( generic.DeleteView):
	model = models.Driver
	success_url = reverse_lazy('drivers:list')


# ==============================================================================
# 							APIView
# ==============================================================================


class CustomerListCreateAPIView(generics.ListCreateAPIView):
	queryset = models.Customer.objects.all()
	serializer_class = serializers.CustomerSerializer
	
class CustomerRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
	queryset = models.Customer.objects.all()
	serializer_class = serializers.CustomerSerializer

class PackageListCreateAPIView(generics.ListCreateAPIView):
	queryset = models.Package.objects.all()
	serializer_class = serializers.PackageSerializer

	def get_queryset(self):
		return self.queryset.filter(customer_id=self.kwargs.get('customer_pk'))

	def perform_create(self, serializer):
		customer = get_object_or_404(models.Customer, pk = self.kwargs.get('customer_pk'))
		serializer.save(customer = customer)
	
class PackageRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
	queryset = models.Package.objects.all()
	serializer_class = serializers.PackageSerializer

	def get_object(self):
		return get_object_or_404(self.get_queryset(), customer_id = self.kwargs.get('customer_pk'), pk=self.kwargs.get('pk'))

class CustomerViewSet(viewsets.ModelViewSet):
	queryset = models.Customer.objects.all()
	serializer_class = serializers.CustomerSerializer
	permission_classes = (permissions.DjangoModelPermissions,)


	@detail_route(methods=['get'])
	def packages(self, request, pk=None):
		self.pagination_class.page_size = 1
		packages = models.Package.objects.filter(customer_id=pk)

		page = self.paginate_queryset(packages)
		if page is not None:
			serializer = serializers.PackageSerializer(page, many=True)
			return self.get_paginated_response(serializer.data)

		# customer = self.get_object()
		
		serializer = serializers.PackageSerializer(packages, many=True)
		return Response(serializer.data)

class PackageViewSet(mixins.CreateModelMixin,
					mixins.ListModelMixin,
					mixins.RetrieveModelMixin,
					mixins.UpdateModelMixin,
					mixins.DestroyModelMixin,
					viewsets.GenericViewSet):
	queryset = models.Package.objects.all()
	serializer_class = serializers.PackageSerializer















	

customers/templates/customers/customer_confirm_delete.html
{% extends "layout.html" %}
{% load materializecss %}

{% block title_tag %}
Customer Delete
{% endblock %}
{% block body_content %}
<h1>Customer form</h1>
<form action="" method="post">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete">
	<a href="{% url 'customers:list' %}">Cancel</a>
</form>
{% endblock %}

customers/templates/customers/driver_confirm_delete.html
{% extends "layout.html" %}
{% load materializecss %}

{% block title_tag %}
Driver Delete
{% endblock %}
{% block body_content %}
<h3 style="margin: 10px 160px">Driver form</h3>
<form action="" method="post" style="margin: 10px 160px">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="waves-effect waves-light btn">
	<a href="{% url 'customers:list' %}">Cancel</a>
</form>
</br>
{% endblock %}

customers/templates/customers/driver_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load rest_framework %}

{% block title_tag %}
Driver Detail
{% endblock %}

{% block body_content %}
<br>
<div>
	<ul style="margin: 10px 160px">
		<li>Name: {{driver.name}}</li>
		<li>Photo: {{driver.photo_url}}</li>
		<li>Email: {{driver.email}}</li>
		<li>Address: {{driver.address_line_1}}</li>
		<li>City: {{driver.address_city}}</li>
		<li>State: {{driver.address_state}}</li>
		<li>Zipcode: {{driver.address_zipcode}}</li>
	</ul>
	
</div>
<br>
{% endblock %}

customers/templates/customers/driver_edit.html
{% extends "layout.html" %}
{% load materializecss %}

{% block title_tag %}
Driver Edit
{% endblock %}
{% block body_content %}
<h1>Driver form</h1>
<form action="" method="post">
	{% csrf_token %}
	{{ form|materializecss }}
	<input type="submit" value="Edit" class="waves-effect waves-light btn">
</form>
{% endblock %}

customers/templates/customers/driver_form.html
{% extends "layout.html" %}
{% load materializecss %}

{% block title_tag %}
Driver Form
{% endblock %}
{% block body_content %}
<br>
<h3 style="margin: 0 100px">Driver form</h3>
<form action="" method="post" style="margin: 0 100px">
	{% csrf_token %}
	{{ form|materializecss }}
	<input type="submit" value="Create" class="waves-effect waves-light btn">
</form>
<br>
{% endblock %}

customers/templates/customers/driver_list.html
{% extends "layout.html" %} {% load static from staticfiles %} {% block title_tag %} Driver List {% endblock %} {% block body_content %}
<div>
    <ul style="margin: 20px 160px">
        {% for driver in drivers %}
        <li>
            {{ driver.name }}
            <span><a href="{% url 'customers:detail' pk=driver.id %}">View Detail</a></span>
            <span><a href="{% url 'customers:update' pk=driver.id %}">Update Profile</a></span>
            <span><a href="{% url 'customers:delete' pk=driver.id %}">Delete Profile</a></span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}